#!/bin/bash

getFolder() {
    if [[ "$1" == "mp3" ]]; then
        link=$2
        echo "[Rip] mp3 mode"
        args="-x --audio-format mp3"
        cd ~/Music/
    else
        link=$1
        args=""
        cd ~/Videos/
    fi
}

parseLink() {
    fullDomain=$(\
        echo "$link" |\
        sed -E 's/https?:\/\/([^\/]+).*/\1/'\
    )
    noSubDomain=$(\
        echo "$fullDomain." |\
        awk -F"." -v end="$(($(echo "$fullDomain." | awk -F"." '{print NF}')-1))" '{print $(end-1)"."$end}'\
    )
    local tmp=$(echo "$noSubDomain" | awk -F"." '{print $1}')
    websiteName="${tmp^}"
    if [[ "$websiteName" == "" ]]; then
        websiteName="Generic"
    fi
    echo "[Rip] $websiteName Video"
}

loadConfig() {
    file="~/.config/video-ripper/$fullDomain.config"
    if test -f "$file"; then
        echo "[Rip] Loading config for $fullDomain"
        config="$(head $file)"
    else
        echo "[Rip] No config for $fullDomain, loading generic config"
        config="bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    fi
}

downloadVideo() {
    mkdir ./$websiteName 2>/dev/null
    cd ./$websiteName
    echo "[Rip] Grabbing Title"
    local title=$(yt-dlp $args -f "$config" "$link" --skip-download --restrict-filenames --print filename)
    echo "[Rip] Downloading: $title..."
    yt-dlp $args -f "$config" "$link" --restrict-filenames
    testSuccess $? "$title"
    exit
}
1
testSuccess() {
    if [[ $1 -eq 0 ]]; then
        nautilus ./$2
        if [[ $? -ne 0 ]]; then
            xdg-open .
        fi
        echo "[Rip] Done"
    else
        echo "[Rip] Something went wrong"
    fi
}

# main
getFolder $1 $2
parseLink
loadConfig
downloadVideo
