#!/bin/bash

testSuccess() {
    if [[ $1 -eq 0 ]]; then
        nohup nautilus ./ &
        echo "Done"
    else
        echo "Something went wrong"
    fi
}

cd ~/Videos/

if [[ $1 == *"www.youtube.com"* ]] || [[ $1 == *"youtu.be"* ]]; then
    echo "Downloading Youtube Video..."
    yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "$1"
    testSuccess $?
    exit
fi

if [[ $1 == *"twitter.com"* ]]; then
    echo "Downloading Twitter Video..."
    yt-dlp "$1"
    testSuccess $?
    exit
fi

if [[ $1 == *"www.reddit.com"* ]] || [[ $1 == *"redd.it"* ]]; then
    echo "Downloading Reddit Video..."
    yt-dlp "$1"
    testSuccess $?
    exit
fi

echo "Website is unknown"
read -p "Attempt to download anyways? [Y/n] " response

case $response in [yY][eE][sS]|[yY]|[jJ]|'') 
    
    echo "Attempting To Downloading Video..."
    yt-dlp "$1"
    testSuccess $?
    ;;
    *)
    echo "Nothing to do"
    ;;
esac
